# Generated by Django 3.1.2 on 2020-11-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('can_receive_texts', models.BooleanField()),
                ('address_1', models.CharField(max_length=256)),
                ('address_2', models.CharField(max_length=256)),
                ('city', models.CharField(choices=[('Ajax', 'Ajax'), ('Aurora', 'Aurora'), ('Brampton', 'Brampton'), ('Brock', 'Brock'), ('Burlington', 'Burlington'), ('Caledon', 'Caledon'), ('Clarington', 'Clarington'), ('East Gwilimbury', 'East Gwilimbury'), ('East York', 'East York'), ('Etobicoke', 'Etobicoke'), ('Georgina', 'Georgina'), ('Halton Hills', 'Halton Hills'), ('Hamilton', 'Hamilton'), ('King', 'King'), ('Maple', 'Maple'), ('Markham', 'Markham'), ('Milton', 'Milton'), ('Mississauga', 'Mississauga'), ('Newmarket', 'Newmarket'), ('North York', 'North York'), ('Oakville', 'Oakville'), ('Oshawa', 'Oshawa'), ('Pickering', 'Pickering'), ('Richmond Hill', 'Richmond Hill'), ('Scarborough', 'Scarborough'), ('Scugog', 'Scugog'), ('Stouffville', 'Stouffville'), ('Thornhill', 'Thornhill'), ('Toronto', 'Toronto (downtown, east/west ends)'), ('Uxbridge', 'Uxbridge'), ('Vaughan', 'Vaughan'), ('Whitby', 'Whitby'), ('York', 'York')], default='Toronto', max_length=50)),
                ('postal_code', models.CharField(max_length=7)),
                ('notes', models.TextField()),
                ('bipoc', models.BooleanField()),
                ('lgbtq', models.BooleanField()),
                ('has_disability', models.BooleanField()),
                ('immigrant_or_refugee', models.BooleanField()),
                ('housing_issues', models.BooleanField()),
                ('sex_worker', models.BooleanField()),
                ('single_parent', models.BooleanField()),
                ('num_adults', models.PositiveSmallIntegerField()),
                ('num_children', models.PositiveSmallIntegerField()),
                ('children_ages', models.CharField(max_length=256)),
                ('food_allergies', models.TextField()),
                ('food_preferences', models.TextField()),
                ('will_accept_vegan', models.BooleanField(default=True)),
                ('will_accept_vegetarian', models.BooleanField(default=True)),
                ('can_meet_for_delivery', models.BooleanField()),
                ('delivery_details', models.TextField()),
                ('available_days', models.CharField(max_length=256)),
                ('available_time_periods', models.CharField(max_length=256)),
                ('dairy_free', models.BooleanField()),
                ('gluten_free', models.BooleanField()),
                ('halal', models.BooleanField()),
                ('low_carb', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('vegetarian', models.BooleanField()),
                ('on_behalf_of', models.BooleanField()),
                ('recipient_notified', models.BooleanField()),
                ('requester_name', models.CharField(max_length=256, null=True)),
                ('requester_email', models.EmailField(max_length=254, null=True)),
                ('requester_phone_number', models.CharField(max_length=20)),
                ('accept_terms', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
