# Generated by Django 3.1.2 on 2020-11-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
