# Generated by Django 3.1.2 on 2020-11-08 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0004_auto_20201108_2139"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealrequest",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
