# Generated by Django 3.1.2 on 2020-11-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0005_mealrequest_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrequest',
            name='address_2',
            field=models.CharField(blank=True, help_text='Apartment, Unit, or Suite number', max_length=256, verbose_name='Address line 2'),
        ),
    ]
