# Generated by Django 3.1.2 on 2020-11-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0007_auto_20201109_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrequest',
            name='major_intersection',
            field=models.CharField(default='', help_text='List the nearest intersection close to your address to help our drivers', max_length=256, verbose_name='Nearest major intersection'),
            preserve_default=False,
        ),
    ]
