# Generated by Django 3.1.2 on 2020-11-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0014_groceryrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryrequest',
            name='city',
            field=models.CharField(choices=[('Ajax', 'Ajax'), ('Aurora', 'Aurora'), ('Brampton', 'Brampton'), ('Brock', 'Brock'), ('Caledon', 'Caledon'), ('Clarington', 'Clarington'), ('East Gwilimbury', 'East Gwilimbury'), ('East York', 'East York'), ('Etobicoke', 'Etobicoke'), ('Georgina', 'Georgina'), ('King', 'King'), ('Maple', 'Maple'), ('Markham', 'Markham'), ('Mississauga', 'Mississauga'), ('Newmarket', 'Newmarket'), ('North York', 'North York'), ('Oshawa', 'Oshawa'), ('Pickering', 'Pickering'), ('Richmond Hill', 'Richmond Hill'), ('Scarborough', 'Scarborough'), ('Scugog', 'Scugog'), ('Stouffville', 'Stouffville'), ('Thornhill', 'Thornhill'), ('Toronto', 'Toronto (downtown, east/west ends)'), ('Uxbridge', 'Uxbridge'), ('Vaughan', 'Vaughan'), ('Whitby', 'Whitby'), ('York', 'York')], default='Toronto', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='city',
            field=models.CharField(choices=[('Ajax', 'Ajax'), ('Aurora', 'Aurora'), ('Brampton', 'Brampton'), ('Brock', 'Brock'), ('Caledon', 'Caledon'), ('Clarington', 'Clarington'), ('East Gwilimbury', 'East Gwilimbury'), ('East York', 'East York'), ('Etobicoke', 'Etobicoke'), ('Georgina', 'Georgina'), ('King', 'King'), ('Maple', 'Maple'), ('Markham', 'Markham'), ('Mississauga', 'Mississauga'), ('Newmarket', 'Newmarket'), ('North York', 'North York'), ('Oshawa', 'Oshawa'), ('Pickering', 'Pickering'), ('Richmond Hill', 'Richmond Hill'), ('Scarborough', 'Scarborough'), ('Scugog', 'Scugog'), ('Stouffville', 'Stouffville'), ('Thornhill', 'Thornhill'), ('Toronto', 'Toronto (downtown, east/west ends)'), ('Uxbridge', 'Uxbridge'), ('Vaughan', 'Vaughan'), ('Whitby', 'Whitby'), ('York', 'York')], default='Toronto', max_length=50, verbose_name='City'),
        ),
    ]
