# Generated by Django 3.1.2 on 2020-11-25 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0016_auto_20201125_0010"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groceryrequest",
            name="available_days",
        ),
        migrations.RemoveField(
            model_name="groceryrequest",
            name="available_time_periods",
        ),
        migrations.RemoveField(
            model_name="mealrequest",
            name="available_days",
        ),
        migrations.RemoveField(
            model_name="mealrequest",
            name="available_time_periods",
        ),
    ]
