# Generated by Django 3.1.2 on 2020-11-28 14:00

import core.models
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipients", "0020_auto_20201127_0210"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groceryrequest",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mealrequest",
            options={},
        ),
        migrations.AlterField(
            model_name="delivery",
            name="deliverer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(core.models.get_sentinel_user),
                related_name="assigned_deliverer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="dropoff_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="dropoff_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="pickup_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="pickup_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="groceryrequest",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="mealrequest",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="updatenote",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
