# Generated by Django 3.1.2 on 2020-11-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0024_auto_20201128_1441"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="container_delivery",
        ),
    ]
