# Generated by Django 3.1.2 on 2020-11-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0026_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryrequest',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='mealrequest',
            name='delivery_date',
        ),
    ]
