# Generated by Django 3.1.2 on 2020-11-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0029_auto_20201128_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateNote',
        ),
    ]
