# Generated by Django 3.1.2 on 2020-12-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0035_auto_20201205_1755"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealrequest",
            name="kosher",
            field=models.BooleanField(default=False, verbose_name="Kosher"),
            preserve_default=False,
        ),
    ]
