# Generated by Django 3.1.2 on 2020-12-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0036_mealrequest_kosher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryrequest',
            name='city',
            field=models.CharField(choices=[('East York', 'East York'), ('Etobicoke', 'Etobicoke'), ('North York', 'North York'), ('Scarborough', 'Scarborough'), ('Toronto', 'Toronto'), ('York', 'York')], default='Toronto', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='city',
            field=models.CharField(choices=[('East York', 'East York'), ('Etobicoke', 'Etobicoke'), ('North York', 'North York'), ('Scarborough', 'Scarborough'), ('Toronto', 'Toronto'), ('York', 'York')], default='Toronto', max_length=50, verbose_name='City'),
        ),
    ]
