# Generated by Django 3.1.2 on 2020-12-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0037_grocerydelivery_grocerydeliverycomment'),
        ('recipients', '0037_auto_20201208_2109'),
    ]

    operations = [
    ]
