# Generated by Django 3.1.2 on 2020-12-12 00:25

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_grocerypickupaddress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipients", "0037_auto_20201208_2109"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroceryDelivery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Unconfirmed", "Unconfirmed"),
                            ("Chef Assigned", "Chef Assigned"),
                            ("Delivery Date Confirmed", "Delivery Date Confirmed"),
                            ("Driver Assigned", "Driver Assigned"),
                            ("Recipient Rescheduled", "Recipient Rescheduled"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Unconfirmed",
                        max_length=256,
                        verbose_name="Status",
                    ),
                ),
                ("date", models.DateField()),
                ("pickup_start", models.TimeField(blank=True, null=True)),
                ("pickup_end", models.TimeField(blank=True, null=True)),
                ("dropoff_start", models.TimeField(blank=True, null=True)),
                ("dropoff_end", models.TimeField(blank=True, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deliverer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(core.models.get_sentinel_user),
                        related_name="delivered_grocery_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pickup_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.grocerypickupaddress",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="recipients.groceryrequest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "grocery deliveries",
            },
        ),
        migrations.CreateModel(
            name="GroceryDeliveryComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(core.models.get_sentinel_user),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="recipients.grocerydelivery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
