# Generated by Django 3.1.2 on 2020-12-11 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_grocerypickupaddress'),
        ('recipients', '0038_merge_20201209_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerydelivery',
            name='dropoff_end',
        ),
        migrations.RemoveField(
            model_name='grocerydelivery',
            name='dropoff_start',
        ),
        migrations.RemoveField(
            model_name='grocerydelivery',
            name='pickup_end',
        ),
        migrations.RemoveField(
            model_name='grocerydelivery',
            name='pickup_start',
        ),
        migrations.AddField(
            model_name='grocerydelivery',
            name='pickup_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grocerypickupaddress'),
        ),
    ]
