# Generated by Django 3.1.2 on 2020-12-21 03:42

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipients', '0040_auto_20201212_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdelivery',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(core.models.get_sentinel_user), related_name='cooked_meal_deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
