# Generated by Django 3.1.2 on 2020-12-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0041_auto_20201220_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerydelivery',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery date'),
        ),
        migrations.AlterField(
            model_name='mealdelivery',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery date'),
        ),
    ]
