# Generated by Django 3.1.2 on 2020-12-29 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0042_auto_20201229_1556'),
        ('recipients', '0042_auto_20201229_1553'),
    ]

    operations = [
    ]
