# Generated by Django 3.1.2 on 2021-01-02 20:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0043_merge_20201229_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryrequest',
            name='condiments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Flour', 'Flour'), ('Sugar', 'Sugar'), ('Tomato Sauce', 'Tomato Sauce')], help_text='Select all that you want', max_length=256, verbose_name='Condiments'),
        ),
        migrations.AlterField(
            model_name='groceryrequest',
            name='fruits',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Apples', 'Apples'), ('Bananas', 'Bananas'), ('Oranges', 'Oranges')], help_text='Select all that you want', max_length=256, verbose_name='Fruits'),
        ),
        migrations.AlterField(
            model_name='groceryrequest',
            name='grains',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Black Beans', 'Black Beans'), ('Chickpeas', 'Chickpeas'), ('Lentils', 'Lentils'), ('Rice', 'Rice'), ('Pasta', 'Pasta')], help_text='Select up to 3', max_length=256, verbose_name='Grains'),
        ),
        migrations.AlterField(
            model_name='groceryrequest',
            name='vegetables',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Carrots', 'Carrots'), ('Garlic', 'Garlic'), ('Onions', 'Onions'), ('Potatoes', 'Potatoes'), ('Spinach', 'Spinach')], help_text='Select all that you want', max_length=256, verbose_name='Vegetables'),
        ),
    ]
