# Generated by Django 3.1.2 on 2021-02-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0045_auto_20210124_2048"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grocerydeliverycomment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="grocerydeliverycomment",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="groceryrequestcomment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="groceryrequestcomment",
            name="subject",
        ),
        migrations.DeleteModel(
            name="GroceryDelivery",
        ),
        migrations.DeleteModel(
            name="GroceryDeliveryComment",
        ),
        migrations.DeleteModel(
            name="GroceryRequest",
        ),
        migrations.DeleteModel(
            name="GroceryRequestComment",
        ),
    ]
