# Generated by Django 3.1.2 on 2021-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0045_auto_20210124_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryrequest',
            name='name',
            field=models.CharField(help_text="This name will be visible within The People's Pantry, if you'd prefer privacy please use your shortened name", max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='name',
            field=models.CharField(help_text="This name will be visible within The People's Pantry, if you'd prefer privacy please use your shortened name", max_length=256, verbose_name='Name'),
        ),
    ]
