# Generated by Django 3.1.2 on 2021-02-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0050_groceryrequestcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryrequest',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery date'),
        ),
    ]
