# Generated by Django 3.1.2 on 2021-02-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0051_groceryrequest_delivery_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groceryrequest",
            name="can_meet_for_delivery",
        ),
    ]
