# Generated by Django 3.1.2 on 2021-02-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0053_groceryrequest_buzzer"),
    ]

    operations = [
        migrations.AddField(
            model_name="groceryrequest",
            name="senior",
            field=models.BooleanField(default=False, verbose_name="Senior citizen"),
            preserve_default=False,
        ),
    ]
