# Generated by Django 3.1.2 on 2021-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0054_groceryrequest_senior'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrequest',
            name='senior',
            field=models.BooleanField(default=False, verbose_name='Senior citizen'),
            preserve_default=False,
        ),
    ]
