# Generated by Django 3.1.2 on 2021-03-17 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0064_auto_20210317_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryrequest',
            name='physical_gift_card',
        ),
    ]
