# Generated by Django 3.1.2 on 2021-04-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0070_transfer_meal_delivery_comments_to_meal_request_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealDeliveryComment',
        ),
    ]
