# Generated by Django 3.1.2 on 2021-04-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0071_delete_mealdeliverycomment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MealDelivery",
        ),
    ]
