# Generated by Django 3.1.2 on 2021-04-12 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0072_delete_mealdelivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealrequest",
            name="dropoff_end",
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AlterField(
            model_name="mealrequest",
            name="dropoff_start",
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name="mealrequest",
            name="pickup_end",
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name="mealrequest",
            name="pickup_start",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
