# Generated by Django 3.1.2 on 2021-05-08 19:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0076_mealrequest_containers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryrequest',
            name='postal_code',
            field=models.CharField(max_length=7, validators=[core.models.validate_toronto_postal_code], verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='postal_code',
            field=models.CharField(max_length=7, validators=[core.models.validate_toronto_postal_code], verbose_name='Postal code'),
        ),
    ]
