# Generated by Django 3.1.2 on 2021-06-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0077_auto_20210508_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryrequest',
            name='gift_card',
        ),
    ]
