# Generated by Django 3.1.2 on 2021-06-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0077_auto_20210508_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrequest',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Unconfirmed', 'Selected'), ('Chef Assigned', 'Chef Assigned'), ('Driver Assigned', 'Driver Assigned'), ('Delivery Date Confirmed', 'Delivery Date Confirmed'), ('Delivered', 'Delivered'), ('Unsuccessful', 'Unsuccessful'), ('Not Selected', 'Not Selected')], default='Submitted', max_length=256, verbose_name='Status'),
        ),
    ]
