# Generated by Django 3.1.13 on 2022-01-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0081_remove_groceryrequest_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groceryrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Submitted", "Submitted"),
                    ("Selected", "Selected"),
                    ("Delivered", "Delivered"),
                    ("Unsuccessful", "Unsuccessful"),
                    ("Not Selected", "Not Selected"),
                ],
                default="Selected",
                max_length=256,
                verbose_name="Status",
            ),
        ),
    ]
