# Generated by Django 3.1.13 on 2022-04-20 02:19

from django.db import migrations


def update_statuses(apps, _schema_editor):
    # Getting rid of the "Not Selected" status, change all existing to "Unsuccessful"
    GroceryRequest = apps.get_model('recipients', 'GroceryRequest')
    GroceryRequest.objects.filter(status='Not Selected').update(status='Unsuccessful')
    MealRequest = apps.get_model('recipients', 'MealRequest')
    MealRequest.objects.filter(status='Not Selected').update(status='Unsuccessful')


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0083_auto_20220419_2219'),
    ]

    operations = [
        migrations.RunPython(update_statuses, reverse_code=migrations.RunPython.noop),
    ]
