# Generated by Django 3.1.13 on 2022-04-20 09:51

from django.db import migrations


def update_statuses(apps, _schema_editor):
    # Getting rid of the "Selected" status, change all existing to "Submitted"
    GroceryRequest = apps.get_model("recipients", "GroceryRequest")
    GroceryRequest.objects.filter(status="Selected").update(status="Submitted")
    MealRequest = apps.get_model("recipients", "MealRequest")
    MealRequest.objects.filter(status="Selected").update(status="Submitted")


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0085_auto_20220420_0918"),
    ]

    operations = [
        migrations.RunPython(update_statuses, reverse_code=migrations.RunPython.noop),
    ]
