# Generated by Django 3.1.13 on 2022-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0086_update_statuses_20220420_0948 '),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryrequest',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Delivered', 'Delivered'), ('Unsuccessful', 'Unsuccessful')], default='Submitted', max_length=256, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Chef Assigned', 'Chef Assigned'), ('Driver Assigned', 'Driver Assigned'), ('Delivery Date Confirmed', 'Delivery Date Confirmed'), ('Delivered', 'Delivered'), ('Unsuccessful', 'Unsuccessful')], default='Submitted', max_length=256, verbose_name='Status'),
        ),
    ]
