# Generated by Django 3.1.2 on 2020-12-08 02:02

from django.db import migrations


def set_site_domain_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    db_alias = schema_editor.connection.alias
    try:
        site = Site.objects.using(db_alias).get(id=1)
    except Site.DoesNotExist:
        site = Site()
    site.name = 'ThePeoplesPantryTO.com'
    site.domain = 'thepeoplespantryto.com'
    site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_chef_permission'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(set_site_domain_name)
    ]
