# Generated by Django 3.1.2 on 2020-12-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20201207_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryPickupAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(help_text='Street name and number', max_length=256, verbose_name='Address line 1')),
                ('address_2', models.CharField(blank=True, help_text='Apartment, Unit, or Suite number', max_length=256, verbose_name='Address line 2')),
                ('city', models.CharField(choices=[('East York', 'East York'), ('Etobicoke', 'Etobicoke'), ('North York', 'North York'), ('Scarborough', 'Scarborough'), ('Toronto', 'Toronto'), ('York', 'York')], default='Toronto', max_length=50, verbose_name='City')),
                ('postal_code', models.CharField(max_length=7, verbose_name='Postal code')),
                ('anonymized_latitude', models.FloatField(blank=True, default=43.65107)),
                ('anonymized_longitude', models.FloatField(blank=True, default=-79.347015)),
                ('name', models.CharField(max_length=256, verbose_name='Name of volunteer responsible for this address')),
                ('phone_number', models.CharField(help_text='Use the format 555-555-5555', max_length=20, verbose_name='Phone number of volunteer responsible for this address')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address if applicable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
