# Generated by Django 3.1.2 on 2021-02-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_grocerypickupaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroceryPickupAddress',
        ),
    ]
