# Generated by Django 3.1.2 on 2020-11-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_auto_20201117_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='training_complete',
            field=models.BooleanField(default=False, verbose_name='Training Complete'),
        ),
    ]
