# Generated by Django 3.1.2 on 2020-11-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0006_volunteer_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="city",
            field=models.CharField(
                choices=[
                    ("Ajax", "Ajax"),
                    ("Aurora", "Aurora"),
                    ("Brampton", "Brampton"),
                    ("Brock", "Brock"),
                    ("Caledon", "Caledon"),
                    ("Clarington", "Clarington"),
                    ("East Gwilimbury", "East Gwilimbury"),
                    ("East York", "East York"),
                    ("Etobicoke", "Etobicoke"),
                    ("Georgina", "Georgina"),
                    ("King", "King"),
                    ("Maple", "Maple"),
                    ("Markham", "Markham"),
                    ("Mississauga", "Mississauga"),
                    ("Newmarket", "Newmarket"),
                    ("North York", "North York"),
                    ("Oshawa", "Oshawa"),
                    ("Pickering", "Pickering"),
                    ("Richmond Hill", "Richmond Hill"),
                    ("Scarborough", "Scarborough"),
                    ("Scugog", "Scugog"),
                    ("Stouffville", "Stouffville"),
                    ("Thornhill", "Thornhill"),
                    ("Toronto", "Toronto (downtown, east/west ends)"),
                    ("Uxbridge", "Uxbridge"),
                    ("Vaughan", "Vaughan"),
                    ("Whitby", "Whitby"),
                    ("York", "York"),
                ],
                default="Toronto",
                max_length=50,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="phone_number",
            field=models.CharField(
                help_text="Use the format 555-555-5555",
                max_length=20,
                verbose_name="Phone number",
            ),
        ),
    ]
