# Generated by Django 3.1.2 on 2020-11-27 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("volunteers", "0007_auto_20201125_0011"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volunteer_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
