# Generated by Django 3.1.2 on 2020-11-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_auto_20201127_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='baking_volume',
            field=models.CharField(blank=True, help_text="For BAKERS: how many 'units' of baked goods can you bake each time? E.g. 48 cookies, 24 cinnamon buns, etc", max_length=256, null=True, verbose_name='Baking volume'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='cooking_prefs',
            field=models.CharField(blank=True, help_text='What do you prefer to cook/bake? Check all that apply.', max_length=256, null=True, verbose_name='Cooking type'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='days_available',
            field=models.CharField(help_text='What days of the week are you available to volunteer?', max_length=256, null=True, verbose_name='Days available'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default='volunteer@example.com', max_length=254, verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='food_types',
            field=models.CharField(blank=True, help_text='What kind of meals/baked goods are you able to prepare? Check all that apply.', max_length=256, null=True, verbose_name='Food types'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='have_cleaning_supplies',
            field=models.BooleanField(blank=True, help_text='Do you have cleaning supplies (soap, disinfectant, etc.) to clean your hands and kitchen?', null=True, verbose_name='Cleaning supplies'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='have_ppe',
            field=models.BooleanField(default=False, help_text='Do you have access to personal protective equipment such as masks, gloves, etc?', verbose_name='PPE'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='name',
            field=models.CharField(default='Volunteer name', max_length=256, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='pronouns',
            field=models.CharField(blank=True, help_text='Select all that apply', max_length=256, null=True, verbose_name='Pronouns'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='recurring_time_available',
            field=models.CharField(help_text="Are there any times when you're consistently available? E.g. Mondays from 1-6pm, etc.", max_length=256, null=True, verbose_name='Recurring availability'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='total_hours_available',
            field=models.CharField(help_text='How many hours a week are your willing to volunteer?', max_length=256, null=True, verbose_name='Total commitment'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='transportation_options',
            field=models.CharField(blank=True, help_text='What means of transportation do you have access to for deliveries? Check all that apply.', max_length=256, null=True, verbose_name='Transportation options'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address_1',
            field=models.CharField(help_text='Street name and number', max_length=256, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='postal_code',
            field=models.CharField(max_length=7, verbose_name='Postal code'),
        ),
    ]
