# Generated by Django 3.1.2 on 2020-12-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0012_auto_20201204_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='pronouns',
            field=models.CharField(blank=True, help_text='Please include all of your pronouns', max_length=256, null=True, verbose_name='Pronouns'),
        ),
    ]
