# Generated by Django 3.1.2 on 2021-01-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0014_auto_20201208_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='organizer_teams',
            field=models.CharField(blank=True, max_length=256, verbose_name='Organizer teams'),
        ),
    ]
