# Generated by Django 3.1.2 on 2021-01-02 16:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0016_volunteer_organizer_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='organizer_teams',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Requests', 'Requests'), ('Volunteer Intake', 'Central Volunteer Intake'), ('Chef Coordinators', 'Chefs Coordinators'), ('Deliverer Coordinators', 'Delivery Volunteers Coordinators'), ('Finances', 'Grants and Finances'), ('Tech', 'Tech'), ('Social Media', 'Social Media'), ('Outreach', 'Outreach')], help_text='Which teams would you be interested in joining?', max_length=256, verbose_name='Organizer teams'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='organizer_teams',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Requests', 'Requests'), ('Volunteer Intake', 'Central Volunteer Intake'), ('Chef Coordinators', 'Chefs Coordinators'), ('Deliverer Coordinators', 'Delivery Volunteers Coordinators'), ('Finances', 'Grants and Finances'), ('Tech', 'Tech'), ('Social Media', 'Social Media'), ('Outreach', 'Outreach')], help_text='Which teams would you be interested in joining?', max_length=256, verbose_name='Organizer teams'),
        ),
    ]
