# Generated by Django 3.1.2 on 2021-02-14 14:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0018_volunteer_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="cooking_prefs",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("Cooking", "Cooking"), ("Baking", "Baking")],
                help_text="What do you prefer to cook/bake? Check all that apply.",
                max_length=256,
                null=True,
                verbose_name="Cooking type",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="days_available",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                help_text="What days of the week are you available to volunteer?",
                max_length=256,
                null=True,
                verbose_name="Days available",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="food_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Meat", "Meat"),
                    ("Vegan", "Vegan"),
                    ("Vegetarian", "Vegetarian"),
                    ("Dairy-free", "Dairy-free"),
                    ("Gluten-free", "Gluten-free"),
                    ("Low carb", "Low carb"),
                    ("Halal", "Halal"),
                    ("Kosher", "Kosher"),
                ],
                help_text="What kind of meals/baked goods are you able to prepare? Check all that apply.",
                max_length=256,
                null=True,
                verbose_name="Food types",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="organizer_teams",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Requests", "Requests"),
                    ("Volunteer Intake", "Central Volunteer Intake"),
                    ("Chef Coordinators", "Chefs Coordinators"),
                    ("Deliverer Coordinators", "Delivery Volunteers Coordinators"),
                    ("Finances", "Grants and Finances"),
                    ("Tech", "Tech"),
                    ("Social Media", "Social Media"),
                    ("Outreach", "Outreach"),
                ],
                help_text="Which teams would you be interested in joining?",
                max_length=256,
                verbose_name="Organizer teams",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="transportation_options",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("SUV or Truck", "SUV or Truck"),
                    ("Medium-sized car", "Medium-sized car"),
                    ("Small car", "Small car"),
                    (
                        "Bike - Spring to Fall deliveries only",
                        "Bike - Spring to Fall deliveries only",
                    ),
                    ("Bike - Can deliver in snow", "Bike - Can deliver in snow"),
                    ("Pedestrian", "Pedestrian"),
                    ("Public Transit", "Public Transit"),
                ],
                help_text="What means of transportation do you have access to for deliveries? Check all that apply.",
                max_length=256,
                null=True,
                verbose_name="Transportation options",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="organizer_teams",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Requests", "Requests"),
                    ("Volunteer Intake", "Central Volunteer Intake"),
                    ("Chef Coordinators", "Chefs Coordinators"),
                    ("Deliverer Coordinators", "Delivery Volunteers Coordinators"),
                    ("Finances", "Grants and Finances"),
                    ("Tech", "Tech"),
                    ("Social Media", "Social Media"),
                    ("Outreach", "Outreach"),
                ],
                help_text="Which teams would you be interested in joining?",
                max_length=256,
                verbose_name="Organizer teams",
            ),
        ),
    ]
