# Generated by Django 3.1.2 on 2021-01-02 18:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0018_auto_20210102_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='cooking_prefs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cooking', 'Cooking'), ('Baking', 'Baking')], help_text='What do you prefer to cook/bake? Check all that apply.', max_length=256, null=True, verbose_name='Cooking type'),
        ),
    ]
