# Generated by Django 3.1.2 on 2021-01-02 18:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0019_auto_20210102_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='food_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Meat', 'Meat'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Dairy-free', 'Dairy-free'), ('Gluten-free', 'Gluten-free'), ('Low carb', 'Low carb'), ('Halal', 'Halal'), ('Kosher', 'Kosher')], help_text='What kind of meals/baked goods are you able to prepare? Check all that apply.', max_length=256, null=True, verbose_name='Food types'),
        ),
    ]
