# Generated by Django 3.1.2 on 2021-01-02 18:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0020_auto_20210102_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='days_available',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='What days of the week are you available to volunteer?', max_length=256, null=True, verbose_name='Days available'),
        ),
    ]
