# Generated by Django 3.1.2 on 2021-01-02 19:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0021_auto_20210102_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='transportation_options',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SUV or Truck', 'SUV or Truck'), ('Medium-sized car', 'Medium-sized car'), ('Small car', 'Small car'), ('Bike - Spring to Fall deliveries only', 'Bike - Spring to Fall deliveries only'), ('Bike - Can deliver in snow', 'Bike - Can deliver in snow'), ('Pedestrian', 'Pedestrian'), ('Public Transit', 'Public Transit')], help_text='What means of transportation do you have access to for deliveries? Check all that apply.', max_length=256, null=True, verbose_name='Transportation options'),
        ),
    ]
