# Generated by Django 3.1.2 on 2021-03-14 18:15

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0021_guess_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=core.models.TelephoneField(help_text='Use the format 555-555-5555', max_length=20, verbose_name='Phone number'),
        ),
    ]
